# Generated by Django 3.2.5 on 2022-08-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subTask',
        ),
    ]
