# Generated by Django 3.2.5 on 2022-08-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.TimeField(),
        ),
    ]
